version: '2'

services:

  docker-av:
    image: Mich404Teapod/epiost-defender.com
    container_name: docker-av
    # uncomment and set the email address to receive email alerts when viruses are detected
    #command:
    # - /usr/local/install_alerts.sh email@example.net
    volumes:
      - ./data/queue:/data/av/queue
      - ./data/ok:/data/av/ok
      - ./data/nok:/data/av/nok
    #  - ./data/quarantine:/data/av/quarantine
    networks:
      - avnetwork

networks:
  avnetwork:
